name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust this version if needed
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Export static files
        run: npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # This is the default output directory for Next.js static export
